# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import coglib.spotify.vectors.sims_pb2 as sims__pb2


class VectorsStub(object):
  """Missing associated documentation comment in .proto file."""

  def __init__(self, channel):
    """Constructor.

    Args:
        channel: A grpc.Channel.
    """
    self.GetVectors = channel.unary_unary(
      "/spotify.vectors.v1.Vectors/GetVectors",
      request_serializer=sims__pb2.GetVectorsRequest.SerializeToString,
      response_deserializer=sims__pb2.GetVectorsResponse.FromString,
    )


class VectorsServicer(object):
  """Missing associated documentation comment in .proto file."""

  def GetVectors(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")


def add_VectorsServicer_to_server(servicer, server):
  rpc_method_handlers = {
    "GetVectors": grpc.unary_unary_rpc_method_handler(
      servicer.GetVectors,
      request_deserializer=sims__pb2.GetVectorsRequest.FromString,
      response_serializer=sims__pb2.GetVectorsResponse.SerializeToString,
    ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
    "spotify.vectors.v1.Vectors", rpc_method_handlers
  )
  server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Vectors(object):
  """Missing associated documentation comment in .proto file."""

  @staticmethod
  def GetVectors(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/spotify.vectors.v1.Vectors/GetVectors",
      sims__pb2.GetVectorsRequest.SerializeToString,
      sims__pb2.GetVectorsResponse.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )
