# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sims.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
  b'\n\nsims.proto\x12\x12spotify.vectors.v1"%\n\x06Vector\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02"|\n\x11GetVectorsRequest\x12\x0c\n\x04uris\x18\x01 \x03(\t\x12!\n\x19\x65xclude_estimated_vectors\x18\x02 \x01(\x08\x12\r\n\x05model\x18\x03 \x01(\t\x12\r\n\x05\x62\x61tch\x18\x04 \x01(\t\x12\x18\n\x10user_vector_type\x18\x05 \x01(\t"\x9e\x01\n\x12GetVectorsResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\r\n\x05\x62\x61tch\x18\x02 \x01(\t\x12=\n\x10\x64istance_measure\x18\x03 \x01(\x0e\x32#.spotify.vectors.v1.DistanceMeasure\x12+\n\x07vectors\x18\x04 \x03(\x0b\x32\x1a.spotify.vectors.v1.Vector*J\n\x0f\x44istanceMeasure\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x43OSINE\x10\x01\x12\x0f\n\x0b\x44OT_PRODUCT\x10\x02\x12\r\n\tEUCLIDEAN\x10\x03\x32h\n\x07Vectors\x12]\n\nGetVectors\x12%.spotify.vectors.v1.GetVectorsRequest\x1a&.spotify.vectors.v1.GetVectorsResponse"\x00\x42.\n\x1c\x63om.spotify.vectors.v1.protoB\x0cVectorProtosP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sims_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals["DESCRIPTOR"]._options = None
  _globals[
    "DESCRIPTOR"
  ]._serialized_options = b"\n\034com.spotify.vectors.v1.protoB\014VectorProtosP\001"
  _globals["_DISTANCEMEASURE"]._serialized_start = 360
  _globals["_DISTANCEMEASURE"]._serialized_end = 434
  _globals["_VECTOR"]._serialized_start = 34
  _globals["_VECTOR"]._serialized_end = 71
  _globals["_GETVECTORSREQUEST"]._serialized_start = 73
  _globals["_GETVECTORSREQUEST"]._serialized_end = 197
  _globals["_GETVECTORSRESPONSE"]._serialized_start = 200
  _globals["_GETVECTORSRESPONSE"]._serialized_end = 358
  _globals["_VECTORS"]._serialized_start = 436
  _globals["_VECTORS"]._serialized_end = 540
# @@protoc_insertion_point(module_scope)
