# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from .usertrackplays_pb2 import UserTrackPlaysRequest, TrackEpisodePlaysAndSkips

class UserTrackPlaysServiceStub(object):
    """The user-track-plays service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/spotify.usertrackplays.v0.UserTrackPlaysService/get',
                request_serializer=UserTrackPlaysRequest.SerializeToString,
                response_deserializer=TrackEpisodePlaysAndSkips.FromString,
                )


class UserTrackPlaysServiceServicer(object):
    """The user-track-plays service
    """

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserTrackPlaysServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=UserTrackPlaysRequest.FromString,
                    response_serializer=TrackEpisodePlaysAndSkips.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spotify.usertrackplays.v0.UserTrackPlaysService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserTrackPlaysService(object):
    """The user-track-plays service
    """

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spotify.usertrackplays.v0.UserTrackPlaysService/get',
            UserTrackPlaysRequest.SerializeToString,
            TrackEpisodePlaysAndSkips.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
